### ISSUE TITLE
Spin labels not the same height

### ISSUE THREAD

**Issue by rlica** [spaulaus/LevelScheme#2]
Line 281, the  "0.35 mult" is making some spin labels higher than others, depending on dE

A constant offset (2.0 add) seems to work well:

 %Set the spin for the energy level
   LevelStart dx3 dx4 add sub Elevel 2.0 add moveto spn
   Ifont setfont spn getnum upshw

   %Set the log(ft)
   LevelStart -2.5 cm add Elevel 2.0 add moveto ft
   Ifont setfont ft getnum upshw

   %Set the feeding
   LevelStart -4. cm add Elevel 2.0 add moveto feed
   Ifont setfont feed getnum upshw

Other than this, great work ;)

**Comment by spaulaus** [comment]
Fixed in commit : 7367b8720c462931b7c3c931d6457e86c8d50c92

Along with a few other issues.
